spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.31.136.171/sell?characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql:true
server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /Users/y1271752959m/Documents/project/log
#  file: /Users/y1271752959m/Documents/project/log/sell.log
#  level: debug
